### PR TITLE
Correct the license to that of upstream compiler-rt

### PR DESCRIPTION
**Pull request by brson**
As this is a derivative work we must maintain the same license terms.

This changes the license to NCSA or MIT instead of Apache 2 or MIT. Since @japaric, @mattico, and @Amanieu have not contributed their work under NCSA they need to sign off on this PR before merging.

Alternately we can simply drop Apache 2 and continue with solely MIT, but that restricts any contributions back upstream, which are unlikely, but could theoretically happen. Better to be compatible if we can.

### CODE REVIEW

**Comment by mattico** [comment]
👍 I meant to bring this up earlier.

I agree to relicense my contributions under the NCSA license with no other restrictions or conditions.

**Comment by japaric** [comment]
I agree to relicense my contributions under the MIT+NCSA license with no other restrictions or conditions.

**Comment by Amanieu** [comment]
I agree to relicense my contributions under the MIT+NCSA license with no other restrictions or conditions.

**Comment by japaric** [comment]
@alexcrichton also needs to sign off

**Comment by alexcrichton** [comment]
I agree to relicense my contributions under the MIT+NCSA license with no other restrictions or conditions.

**Comment by japaric** [comment]
Thank you all!

**Pull request merged**
